/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ecoana.ui;

// Importaciones de las clases del modelo y DB
import ecoana.model.Cliente;
import ecoana.model.SolicitudReserva;
import ecoana.db.DatabaseManager;

// Importaciones de Swing y AWT
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerNumberModel;

// Importaciones de Utilidades (Fechas, Calendario)
import java.util.Date;
import java.util.Calendar;
import java.text.SimpleDateFormat; // Para el formato del editor de fecha



public class FormularioReserva extends javax.swing.JFrame {
private DatabaseManager dbManager;
    /**
     * Creates new form FormularioReserva
     */
    public FormularioReserva() {
        initComponents();
        dbManager = new DatabaseManager(); // Inicialización
        configurarComponentesAdicionales(); // Método para configurar Spinners/Combo
        this.setTitle("Cabaña Eco-Ana: Solicitud de Reserva"); // Poner título a la ventana
        this.setLocationRelativeTo(null); // Centrar la ventana al abrir
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrimerApellido = new javax.swing.JTextField();
        txtSegundoApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        spnFechaNacimiento = new javax.swing.JSpinner();
        spnFechaIngreso = new javax.swing.JSpinner();
        spnFechaSalida = new javax.swing.JSpinner();
        spnCantidadPersonas = new javax.swing.JSpinner();
        cmbTipoPago = new javax.swing.JComboBox<>();
        chkTerminos = new javax.swing.JCheckBox();
        btnEnviarSolicitud = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NOMBRE: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 30, -1, -1));

        jLabel2.setText("PRIMER APELLIDO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 86, -1, -1));

        jLabel3.setText("SEGUNDO APELLIDO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 142, -1, -1));

        jLabel4.setText("CÉDULA / ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 204, -1, -1));

        jLabel5.setText("TELÉFONO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 260, -1, -1));

        jLabel6.setText("CORREO ELECTRÓNICO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 310, -1, -1));

        jLabel7.setText("FECHA DE NACIMIENTO:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 373, -1, -1));

        jLabel8.setText("FECHA INGRESO:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 415, -1, -1));

        jLabel9.setText("FECHA SALIDA:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 460, -1, -1));

        jLabel10.setText("CANTIDAD DE PERSONAS:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 513, -1, -1));

        jLabel11.setText("TIPO DE PAGO:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 569, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 19, 118, 38));
        getContentPane().add(txtPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 86, 126, 33));
        getContentPane().add(txtSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 134, 113, 33));
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 204, 114, 31));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 257, 122, 35));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 310, 127, 42));
        getContentPane().add(spnFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 370, -1, -1));
        getContentPane().add(spnFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 412, -1, -1));
        getContentPane().add(spnFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 457, -1, -1));
        getContentPane().add(spnCantidadPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 510, -1, -1));

        cmbTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 566, -1, -1));

        chkTerminos.setText("Acepto los términos y condiciones");
        chkTerminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTerminosActionPerformed(evt);
            }
        });
        getContentPane().add(chkTerminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 640, 250, -1));

        btnEnviarSolicitud.setText("Enviar Solicitud de Reserva");
        btnEnviarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarSolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviarSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 594, 252, 166));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkTerminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTerminosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTerminosActionPerformed

    
    
    
    
    
    
    private void btnEnviarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarSolicitudActionPerformed
        // TODO add your handling code here:
        // 1. Recoger Datos del Formulario
    String nombre = txtNombre.getText().trim();
    String pApellido = txtPrimerApellido.getText().trim();
    String sApellido = txtSegundoApellido.getText().trim(); // Asegúrate que este campo exista y tenga nombre txtSegundoApellido
    String cedula = txtCedula.getText().trim();
    String telefono = txtTelefono.getText().trim();
    String correo = txtCorreo.getText().trim();

    // Obtener valores de los Spinners (requiere casting)
    Date fechaNac = (Date) spnFechaNacimiento.getValue();
    Date fechaIn = (Date) spnFechaIngreso.getValue();
    Date fechaOut = (Date) spnFechaSalida.getValue();
    int cantPersonas = (Integer) spnCantidadPersonas.getValue();

    // Obtener valor del ComboBox y CheckBox
    String tipoPago = (String) cmbTipoPago.getSelectedItem();
    boolean terminosOk = chkTerminos.isSelected();

    // 2. Validar Datos (Ejemplo Básico)
    StringBuilder errores = new StringBuilder();
    if (nombre.isEmpty()) errores.append("El nombre es obligatorio.\n");
    if (pApellido.isEmpty()) errores.append("El primer apellido es obligatorio.\n");
    // Segundo apellido puede ser opcional en algunos lugares, ajusta si es necesario
    if (cedula.isEmpty()) errores.append("La cédula o ID es obligatoria.\n");
    if (telefono.isEmpty()) errores.append("El teléfono es obligatorio.\n");
    if (correo.isEmpty()) errores.append("El correo electrónico es obligatorio.\n"); // Podrías añadir validación de formato de email
    if (fechaIn == null) errores.append("La fecha de ingreso es obligatoria.\n");
    if (fechaOut == null) errores.append("La fecha de salida es obligatoria.\n");
    if (fechaIn != null && fechaOut != null && fechaIn.after(fechaOut)) {
         errores.append("La fecha de ingreso no puede ser posterior a la fecha de salida.\n");
    }
    if (!terminosOk) {
        errores.append("Debe aceptar los términos y condiciones.\n");
    }

    // Si hay errores, mostrarlos y detener
    if (errores.length() > 0) {
        JOptionPane.showMessageDialog(this, // Componente padre (el formulario actual)
                                      errores.toString(), // Mensaje de error
                                      "Errores de Validación", // Título de la ventana
                                      JOptionPane.WARNING_MESSAGE); // Tipo de icono
        return; // Salir del método si hay errores
    }

    // 3. Crear Objetos del Modelo
    Cliente cliente = new Cliente(nombre, pApellido, sApellido, cedula, telefono, correo, fechaNac);
    SolicitudReserva solicitud = new SolicitudReserva(cliente, fechaIn, fechaOut, cantPersonas, tipoPago, terminosOk);

    // 4. Intentar Guardar en Base de Datos
    boolean guardadoExitoso = dbManager.guardarSolicitud(solicitud);

    // 5. Mostrar Mensaje al Usuario
    if (guardadoExitoso) {
        JOptionPane.showMessageDialog(this,
                                      "¡Solicitud de reserva enviada con éxito!",
                                      "Solicitud Enviada",
                                      JOptionPane.INFORMATION_MESSAGE);
        limpiarFormulario(); // Limpiar campos después de éxito
    } else {
        JOptionPane.showMessageDialog(this,
                                      "Hubo un error al guardar la solicitud.\nPor favor, revise la conexión a la base de datos o contacte al administrador.",
                                      "Error de Base de Datos",
                                      JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnEnviarSolicitudActionPerformed

    
    
    
    
    
    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    
    
    
    
     private void configurarComponentesAdicionales() {
        // --- Configuración Spinner Cantidad Personas ---
        SpinnerNumberModel modelCant = new SpinnerNumberModel(1, 1, 20, 1);
        spnCantidadPersonas.setModel(modelCant);

        // --- Configuración Spinner Fecha Nacimiento ---
        // ... (el código de configuración de los spinners de fecha) ...
        
        
        
        SpinnerDateModel modelNac = new SpinnerDateModel();
        spnFechaNacimiento.setModel(modelNac);
        JSpinner.DateEditor editorNac = new JSpinner.DateEditor(spnFechaNacimiento, "yyyy-MM-dd");
        spnFechaNacimiento.setEditor(editorNac);

        // --- Configuración Spinner Fecha Ingreso ---
        // ... (el código de configuración) ...
        SpinnerDateModel modelIng = new SpinnerDateModel();
        spnFechaIngreso.setModel(modelIng);
        JSpinner.DateEditor editorIng = new JSpinner.DateEditor(spnFechaIngreso, "yyyy-MM-dd");
        spnFechaIngreso.setEditor(editorIng);

        // --- Configuración Spinner Fecha Salida ---
        // ... (el código de configuración) ...
         SpinnerDateModel modelSal = new SpinnerDateModel();
        spnFechaSalida.setModel(modelSal);
        JSpinner.DateEditor editorSal = new JSpinner.DateEditor(spnFechaSalida, "yyyy-MM-dd");
        spnFechaSalida.setEditor(editorSal);

        // --- Configuración ComboBox Tipo Pago ---
        String[] tiposPago = {"Efectivo", "Depósito", "Sinpe", "Tarjeta", "Paypal", "Cripto", "Otro"};
        cmbTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(tiposPago));
    }
    
    
    
    
    private void limpiarFormulario() {
    txtNombre.setText("");
    txtPrimerApellido.setText("");
    txtSegundoApellido.setText("");
    txtCedula.setText("");
    txtTelefono.setText("");
    txtCorreo.setText("");

    // Resetear Spinners a sus valores iniciales (o a la fecha actual)
    configurarComponentesAdicionales(); // La forma más fácil es volver a configurar todo
    // Alternativa: Poner valores específicos si no quieres llamar a toda la configuración
    // spnCantidadPersonas.setValue(1);
    // Date hoy = new Date();
    // spnFechaNacimiento.setValue(hoy); // O una fecha por defecto
    // spnFechaIngreso.setValue(hoy);
    // Calendar cal = Calendar.getInstance();
    // cal.add(Calendar.DAY_OF_MONTH, 1);
    // spnFechaSalida.setValue(cal.getTime());


    cmbTipoPago.setSelectedIndex(0); // Seleccionar el primer ítem ("Efectivo")
    chkTerminos.setSelected(false);

    txtNombre.requestFocus(); // Poner el foco en el primer campo
}
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    /**
     * El método principal que inicia la aplicación.
     * @param args the command line arguments (no los usamos aquí)
     */
    public static void main(String args[]) {
        /* --- Sección para mejorar la apariencia (Look and Feel) --- */
        // Intenta poner la apariencia "Nimbus" que se ve más moderna
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            // Si hay un problema al poner Nimbus, registra el error (la app funcionará con la apariencia por defecto)
            java.util.logging.Logger.getLogger(FormularioReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* --- Fin de la sección de apariencia --- */


        /* --- Sección para crear y mostrar el formulario de forma segura --- */
        // java.awt.EventQueue.invokeLater asegura que la creación del formulario
        // se haga en el hilo correcto para interfaces gráficas (el Event Dispatch Thread)
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Esta es la línea clave: Crea una nueva instancia de nuestro formulario
                // y la hace visible en la pantalla.
                new FormularioReserva().setVisible(true);
            }
        });
        /* --- Fin de la sección de mostrar formulario --- */
    } // Fin del método main
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarSolicitud;
    private javax.swing.JCheckBox chkTerminos;
    private javax.swing.JComboBox<String> cmbTipoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spnCantidadPersonas;
    private javax.swing.JSpinner spnFechaIngreso;
    private javax.swing.JSpinner spnFechaNacimiento;
    private javax.swing.JSpinner spnFechaSalida;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtSegundoApellido;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
